services:
  dind:
    image: docker:dind
    ports:
      - 2376:2376
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home

  jenkins:
    build:
      context: contextPath
      dockerfile: Dockerfile
    privileged: true
    ports:
      - 8080:8080
      - 5000:5000
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH=: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

volumes:
  jenkins-docker-certs:
  jenkins-data:
